=== Kubon1999/first-website/xml - xml schema/schema.xsd
<?xml versdion="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
attributeFormDefault="unqualified"
elementFormDefault="qualified">

<xs:element name="document">
	<xs:complexType>
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="game">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="section" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="header" type="xs:string" minOccurs="1" maxOccurs="1"/>
									<xs:element name="content">
										<xs:complexType mixed="true">
											<xs:group ref="internal" minOccurs="0" maxOccurs="unbounded" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							<xs:attribute name="category" type="xs:string" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="lang" type="xs:string" default="en"/>
	</xs:complexType>
</xs:element>

<xs:element name="shortcut" type="shortcutType" />

<xs:complexType name="shortcutType">
	<xs:all>
		<xs:element name="short" type="shortType" />
		<xs:element name="full" type="xs:string" />
	</xs:all>
</xs:complexType>

<xs:simpleType name="shortType">
	<xs:restriction base="xs:string">
		<xs:maxLength value="10" />
	</xs:restriction>
</xs:simpleType>

<xs:element name="list">
	<xs:simpleType>
		<xs:list itemType="xs:string" />
	</xs:simpleType>
</xs:element>

<xs:element name="cabinet">
	<xs:complexType>
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="element">
				<xs:complexType mixed="true">
					<xs:sequence>
						<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
						<xs:group ref="internal" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="gallery">
	<xs:complexType>
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="name" type="xs:string" />
			<xs:element ref="img" />
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="link" type="linkType" />

<xs:complexType name="linkType">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="src" type="xs:string" />
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<xs:element name="img" type="linkType" />

<xs:simpleType name="roman">
	<xs:restriction base="xs:string">
		<xs:pattern value="([IVXLCDM])*" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="tier">
	<xs:restriction base="roman">
		<xs:enumeration value="I" />
		<xs:enumeration value="II" />
		<xs:enumeration value="III" />
		<xs:enumeration value="IV" />
		<xs:enumeration value="V" />
		<xs:enumeration value="VI" />
		<xs:enumeration value="VII" />
		<xs:enumeration value="VIII" />
		<xs:enumeration value="IX" />
		<xs:enumeration value="X" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="score">
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="1" />
		<xs:maxInclusive value="10" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="num_tier">
	<xs:union memberTypes="tier score" />
</xs:simpleType>

<xs:element name="tankData">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="type" type="xs:string" />
			<xs:element name="tier" type="num_tier" />
			<xs:element name="country" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="span">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="bold" type="xs:boolean" />
				<xs:attribute name="italic" type="xs:boolean" />
				<xs:attribute name="del" type="xs:boolean" />
				<xs:attribute name="mark" type="xs:boolean" />
				<xs:attribute name="ins" type="xs:boolean" />
				<xs:attribute name="suporsub" type="suporsubType" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>

<xs:simpleType name="suporsubType">
	<xs:restriction base="xs:string">
		<xs:pattern value="sup|sub" />
	</xs:restriction>
</xs:simpleType>

<xs:element name="villageData">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="founder" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="district" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element ref="buildings" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="unsorted" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="buildings" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="buildings">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="building" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="building">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="type" type="buildingType" default="mixed" />
		<xs:attribute name="underconstruction" type="xs:boolean" />
	</xs:complexType>
</xs:element>

<xs:simpleType name="buildingType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="mixed" />
		<xs:enumeration value="productional" />
		<xs:enumeration value="recreational" />
		<xs:enumeration value="defensive" />
		<xs:enumeration value="residential" />
	</xs:restriction>
</xs:simpleType>

<xs:group name="internal">
	<xs:choice>
		<xs:element ref="shortcut" />
		<xs:element ref="list" />
		<xs:element ref="gallery" />
		<xs:element ref="cabinet" />
		<xs:element ref="link" />
		<xs:element ref="span" />

		<xs:element ref="tankData" />
		<xs:element ref="villageData" />
	</xs:choice>
</xs:group>

</xs:schema>

=== Kubon1999/first-website/xml - xml schema/gaming.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schema.xsd"
lang="pl">
	<game>
		<title>World of Tanks</title>
		<section>
			<header>
				Informacje podstawowe
			</header>
			<content>
				Klan:
				<shortcut>
					<short>PGP</short>
					<full>
					Polska Grupa Pancerniaków
					</full>
				</shortcut>
				Skupiony na pojazdach z krajów:
				<list>Ameryka, Brytania</list>
				Skupiony na pojazdach typu:
				<list>Średni, Niszczyciel, Działo samobieżne</list>
			</content>
		</section>
		<section>
			<header>
				Ulubione czołgi
			</header>
			<content>
				<cabinet>
					<element>
						<name>M4 sherman</name>
						<tankData>
							<type>Czołg średni</type>
							<tier>V</tier>
							<country>USA</country>
						</tankData>
					</element>
					<element>
						<name>M26 Pershing</name>
						<tankData>
							<type>Czołg średni</type>
							<tier>VIII</tier>
							<country>USA</country>
						</tankData>
					</element>
					<element>
						<name>M36 Jackson</name>
						<tankData>
							<type>Niszczyciel czołgów</type>
							<tier>VI</tier>
							<country>USA</country>
						</tankData>
					</element>
					<element>
						<name>Alecto</name>
						<tankData>
							<type>Niszczyciel czołgów</type>
							<tier>IV</tier>
							<country>USA</country>
						</tankData>
					</element>
					<element>
						<name>M4A3E2 Sherman Jumbo</name>
						<tankData>
							<type>Czołg średni</type>
							<tier>VI</tier>
							<country>USA</country>
						</tankData>
					</element>
				</cabinet>
			</content>
		</section>
		<section category="gallery">
			<header>
				Galeria
			</header>
			<content>
				<gallery>
					<name>Święta 2017 - Pershing w garażu</name>
					<img src="galleries/gaming/world_of_tanks/World Of Tanks-01-15-2017 18-02-44-949.jpg">Czołg</img>
					<name>Odwiedziny po miesiącach - M46 Patton w garażu</name>
					<img src="galleries/gaming/world_of_tanks/shot_005.jpg">Czołg</img>
				</gallery>
			</content>
		</section>
		<section>
			<header>
				Inne
			</header>
			<content>
				Link do strony gry:
				<link src="https://worldoftanks.eu/pl/">World of Tanks</link>
			</content>
		</section>
	</game>
	<game>
		<title>Medieval Engineers</title>
		<section>
			<header>
				Widok mojej osady ze szczytu góry
			</header>
			<content>
				Chciałem przedstawić jako kolejną z wielu gier w jakie gram, grę która ma cechę wspólną z większością moich gier, a zarazem najbardziej mi bliską, otóż chodzi o <span bold="true">konstruowanie</span>.
				Na poniższym zrzucie ekranowym widać moje kilkadziesiąt godzin przetwarzania zasobów, robienia badań i budowania domów oraz maszyn ułatwiających dalszy rozwój.
				<gallery>
					<name>Wioska ze szczytu</name>
					<img src="galleries/gaming/medieval_engineers/peak.jpg">Szczyt</img>
				</gallery>
				Budynki zbudowane na tym swiecie:
				<villageData>
					<name></name>
					<founder>ja</founder>
					<district>
						<name></name>
						<buildings>
							<building>
								<name>Mój dom</name>
							</building>
							<building type="productional">
								<name>Tartak</name>
							</building>
							<building type="productional">
								<name>Kuźnia</name>
							</building>
							<building type="productional">
								<name>Garncarnia</name>
							</building>
							<building type="productional">
								<name>Szwalnia</name>
							</building>
							<building type="productional">
								<name>Młyn</name>
							</building>
						</buildings>
					</district>
					<district>
						<name></name>
						<buildings>
							<building type="productional">
								<name>Piekarnia</name>
							</building>
							<building type="recreational">
								<name>Gospoda</name>
							</building>
							<building type="productional">
								<name>Garbarnia</name>
							</building>
							<building type="productional">
								<name>Farma</name>
							</building>
						</buildings>
					</district>
					<district>
						<name></name>
						<buildings>
							<building type="defensive">
								<name>Wieża obserwacyjna</name>
							</building>
							<building type="productional">
								<name>Kopalnia</name>
							</building>
						</buildings>
					</district>
					<unsorted>
						<buildings>
							<building type="defensive" underconstruction="true">
								<name>Wieża obronna</name>
							</building>
						</buildings>
					</unsorted>
				</villageData>
			</content>
		</section>
	</game>
</document>
